# **Lab 2: Understanding and Implementing Numpy Tensors and Tensor Operations like Slicing, Broadcasting and Reshaping**

In [ ]:
# Setting up of Tensorflow, Keras and Numpy
import numpy as np
import tensorflow as tf
from tensorflow import keras

In [ ]:
# Everything is Tensor for Numpy
x = np.array(14)
x.ndim # A scalar is a 0-D tensor

0

In [ ]:
x.shape # shape tuple is empty for a 0-D tensor

()

In [ ]:
# A Vector is a 1-D Tensor
x = np.array([14, 21, 34, 78])
x.ndim

1

In [ ]:
x.shape # Shape of a 1-D tensor is (no_of_elements,)

(4,)

In [ ]:
# A Matrix or An array of array is a 2-D Tensor
x = np.array([[14,21,34,78],
              [15,22,35,79],
              [16,23,36,80]])
x.ndim # number of dimensions or rank of a 2-D Tensor

2

In [ ]:
x.shape # shape of a 2-D tensor is a tuple specifying no of elements in each axis

(3, 4)

In [ ]:
# A 3-D Tensor is an array of matrices
x = np.array([[[41,21,34,78],
              [15,72,35,79],
              [16,23,6,80]],

              [[14,21,34,78],
              [15,22,5,79],
              [16,23,36,80]],

              [[14,21,34,78],
              [15,2,35,79],
              [16,23,36,80]],

              [[14,1,34,78],
              [15,22,35,79],
              [16,23,36,80]]
              ])

x.ndim # For a 3-D tensor ndim is 3

3

In [ ]:
x.shape # Shape of a 3-D tensor is (i,j,k) where i is no of matrices,
        # j is no of rows in each matrix and k is no of cols in each matrix

(4, 3, 4)

# Topic 1 - Understanding Tensor Slicing
**Tensor Slicing:** Selecting specific elements in a tensor is called as *tensor slicing*

In [ ]:
from keras.datasets import mnist
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

11490434/11490434 [==============================] - 0s 0us/step


## Tensor Slicing Example 1##
**Selecting a subset of images**

In [ ]:
print(train_images.shape)
my_slice = train_images[10]
print(my_slice.shape) # Select the tenth image from the dataset of 60 K images

(60000, 28, 28)
(28, 28)


In [ ]:
my_slice = train_images[10:100] # Selecting all images from 10th upto 100th (excl 100th)
my_slice.shape # we have selected 90 images

(90, 28, 28)

In [ ]:
my_slice = train_images[10:100,0:28, 0:28] # this is equivalent to previous code
my_slice.shape

(90, 28, 28)

In [ ]:
my_slice = train_images[10:100, :, :] # this is also equivalent
my_slice.shape

(90, 28, 28)

**Tensor Slicing - Exercise 1:** Apply tensor slicing to get the 14 x 14 pixels from the bottom right corner of all images

In [ ]:
my_slice = train_images[:,14:28, 14:28]
my_slice.shape

(60000, 14, 14)

**Tensor Slicing - Exercise 2:** Apply tensor slicing to crop 14 x 14 pixels centered in the middle of each image

In [ ]:
my_slice = train_images[:, 7:21, 7:21]
my_slice.shape

(60000, 14, 14)

In [ ]:
# Alternative way to specify the same using negative indices
my_slice = train_images[:,7:-7, 7:-7]
my_slice.shape

(60000, 14, 14)

**Exercise 3:** Apply tensor slicing to select first three batches of images. Assume batch-size of 128

In [ ]:
batch1 = train_images[0:128] # batch of first 128 images


In [ ]:
batch2 = train_images[128:256] #batch of second set of 128 images
batch2.shape

(128, 28, 28)

In [ ]:
batch3 = train_images[256:384]
batch3.shape

(128, 28, 28)

**Exercise 4:** Try to generalize the selection of batches such that if asked to get nth batch your generalized code can fetch the same. Assume that you get the batch# as a parameter

In [ ]:
n = 0
batch_n = train_images[128* n : 128 * (n+1)]
batch_n.shape

(128, 28, 28)

# Topic 2 - Understanding Broadcasting
The smaller tensor is usually *broadcasted* to match the shape of the larger tensor.
Broadcasting consists of two steps:
1. Axes are added to the smaller tensor to match the ndim of the larger tensor.
2. The smaller tensor is repeated along-side the new axes to match the full shape of the larger tensor

In [ ]:
# Example 1 - Successful Broadcasting

# x is a 1 D tensor with shape (4,)
x = np.array([1,4,6,9])
x.ndim


1

In [ ]:
x.shape

(4,)

In [ ]:
# y is a matrix (i.e., a 2-D tensor) with shape (3,4)
y = np.array([[34,35,36,37],
              [44,45,46,47],
              [54,55,56,57]])
y.ndim

2

In [ ]:
y.shape

(3, 4)

In [ ]:
# They are actually not compatible for tensor operation of addition
# However because of implicit broadcasting the shape of the smaller tensor x will be matched with shape of y
x + y # successful because of broadcasting. Here due to broadcasting x is considered as:
      # [[1,4,6,9],
      #  [1,4,6,9],
      #  [1,4,6,9]] for the tensor operation

array([[35, 39, 42, 46],
       [45, 49, 52, 56],
       [55, 59, 62, 66]])

In [ ]:
x.shape

(4,)

In [ ]:
# Example 2 - Illustrating how broadcasting might fail in certain cases
# If the shape of tensors cannot be made compatible through broadcasting you will get an error
p = np.array([1,2,3,4,5])

q = np.array([[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12]
           ])

In [ ]:
# Here the smaller tensor p has shape (5,)
# The larger tensor q has shape (3,4)
# Thus they cannot be made compatible even through broadcasting.
# Therefore we get error when we try to add them as seen below:
p + q

ValueError: ignored

# Topic 3 - Understanding Tensor Reshaping
Reshaping a tensor means rearranging the elements in the tensor or rearranging its rows and columns to match a target shape.

The reshaped tensor has the same no of elements as the original tensor.

Below are some simple examples of tensor reshaping:



In [ ]:
x = np.array([[1,2,3],
              [4,5,6]])
x.shape

(2, 3)

In [ ]:
x = x.reshape((6,1))
x

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [ ]:
# Transpose operation is an example of reshaping
x = np.array([[1,2,3],
              [4,5,6]])
print(x)


[[1 2 3]
 [4 5 6]]


In [ ]:
x.shape

(2, 3)

In [ ]:
x = np.transpose(x)
print(x)

[[1 4]
 [2 5]
 [3 6]]


In [ ]:
x.shape

(3, 2)